# Generated by Django 3.1.5 on 2021-02-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20210215_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
